services:
  # api:
  #   container_name: api
  #   build: .
  #   restart: "no"
  #   environment:
  #     - TZ=Europe/Moscow
  #   ports:
  #     - 8000:8000
  #     # volumes:
  #     # - api
  #   depends_on: [ mongodb ]

  mongodb:
    container_name: mongodb
    image: mongo:7.0
    restart: "always"
    networks:
      - mongo-network
    ports:
      - 27017:27017
    volumes:
      - capify:/data/db
    env_file:
      - .env

  mongo-express:
    container_name: mongodb-express
    image: mongo-express
    restart: "always"
    networks:
      - mongo-network
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - capify:/data/db
    env_file:
      - .env

volumes:
  capify:


networks:
  mongo-network:
    driver: bridge
